name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # The OIDC ID token is used for authentication with JSR and npm.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v2.x

      - name: Setup Node (needed for npm OIDC)
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Ensure npm >= 11.5.1
        run: npm install -g npm@latest

      - name: Bump project verison
        run: deno task version ${{ inputs.version }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "bump version"

      - name: Publish to JSR
        run: deno publish

      - name: Build npm package
        run: deno task npm ${{ inputs.version }}

      - name: Publish to npm
        run: |
          deno task npm ${{ inputs.version }}
          cd npm
          npm publish --access public

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: true
